development:
  adapter: postgresql
  encoding: unicode
  database: adamgoodapp_development
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: adamgoodapp_production
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: adamgoodapp_test
  pool: 5